# Generated by Django 4.1 on 2023-12-11 17:13

from django.db import migrations, models
import netfields.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssignableIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_ip",
                    netfields.fields.InetAddressField(
                        blank=True, default=None, max_length=39, null=True
                    ),
                ),
                ("network", netfields.fields.CidrAddressField(max_length=43)),
            ],
        ),
        migrations.AddConstraint(
            model_name="assignableip",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("network__net_contains", models.F("current_ip")),
                    ("current_ip__isnull", True),
                    _connector="OR",
                ),
                name="ip_in_range",
            ),
        ),
    ]
